In [97]:
import pandas as pd
import numpy as np

In [98]:
df = pd.read_csv('all_reviews_with_full_nlp_analysis.csv')

In [99]:
df.head()

,unnamed:_0,name,review,date_old,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications
0,0,Vladimiro Mascaro,3.0,"Friday, October 11, 2024 at 06:25:37 p.m.",1,amazon,United Kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...","[{'name': 'orders', 'type': 'OTHER', 'salience...",Negative,NaN,since july until this month of all my orders 8...,"[{'text': 'since', 'part_of_speech': 'ADP'}, {...",en,"[{'category': '/Shopping', 'confidence': 0.629..."
1,1,Lucy Loo,9.0,"Friday, October 11, 2024 at 09:57:32 a.m.",1,amazon,United Kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,as a family we order from amazon almost daily ...,"[{'text': 'as', 'part_of_speech': 'ADP'}, {'te...",en,[]
2,2,Da,21.0,"Thursday, October 10, 2024 at 11:36:09 a.m.",5,amazon,United Kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...","[{'name': 'store', 'type': 'LOCATION', 'salien...",Positive,probably the only store that 1 delivers ontime...,NaN,"[{'text': 'probably', 'part_of_speech': 'ADV'}...",en,[]
3,3,Vicki Study,1.0,"Friday, October 11, 2024 at 03:36:33 p.m.",1,amazon,United Kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...","[{'name': 'customer service', 'type': 'OTHER',...",Negative,NaN,the customer service has been absolutely appal...,"[{'text': 'the', 'part_of_speech': 'DET'}, {'t...",en,[]
4,4,Jeffrey Bruce,5.0,"Thursday, October 10, 2024 at 05:09:02 p.m.",1,amazon,United Kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,amazon are quick enough to take payment for or...,"[{'text': 'amazon', 'part_of_speech': 'NOUN'},...",en,"[{'category': '/Shopping', 'confidence': 0.629..."

In [100]:
df.drop(columns=['unnamed:_0'], inplace=True)

In [101]:
df.head()

,name,review,date_old,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications
0,Vladimiro Mascaro,3.0,"Friday, October 11, 2024 at 06:25:37 p.m.",1,amazon,United Kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...","[{'name': 'orders', 'type': 'OTHER', 'salience...",Negative,NaN,since july until this month of all my orders 8...,"[{'text': 'since', 'part_of_speech': 'ADP'}, {...",en,"[{'category': '/Shopping', 'confidence': 0.629..."
1,Lucy Loo,9.0,"Friday, October 11, 2024 at 09:57:32 a.m.",1,amazon,United Kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,as a family we order from amazon almost daily ...,"[{'text': 'as', 'part_of_speech': 'ADP'}, {'te...",en,[]
2,Da,21.0,"Thursday, October 10, 2024 at 11:36:09 a.m.",5,amazon,United Kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...","[{'name': 'store', 'type': 'LOCATION', 'salien...",Positive,probably the only store that 1 delivers ontime...,NaN,"[{'text': 'probably', 'part_of_speech': 'ADV'}...",en,[]
3,Vicki Study,1.0,"Friday, October 11, 2024 at 03:36:33 p.m.",1,amazon,United Kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...","[{'name': 'customer service', 'type': 'OTHER',...",Negative,NaN,the customer service has been absolutely appal...,"[{'text': 'the', 'part_of_speech': 'DET'}, {'t...",en,[]
4,Jeffrey Bruce,5.0,"Thursday, October 10, 2024 at 05:09:02 p.m.",1,amazon,United Kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,amazon are quick enough to take payment for or...,"[{'text': 'amazon', 'part_of_speech': 'NOUN'},...",en,"[{'category': '/Shopping', 'confidence': 0.629..."

In [102]:
df['name'] = df['name'].str.strip().str.lower()

In [103]:
df.drop(columns=['date_old'], inplace=True)

In [104]:
df['country'] = df['country'].str.strip().str.lower()

In [105]:
df.head(2)

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...","[{'name': 'orders', 'type': 'OTHER', 'salience...",Negative,NaN,since july until this month of all my orders 8...,"[{'text': 'since', 'part_of_speech': 'ADP'}, {...",en,"[{'category': '/Shopping', 'confidence': 0.629..."
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,as a family we order from amazon almost daily ...,"[{'text': 'as', 'part_of_speech': 'ADP'}, {'te...",en,[]

In [106]:
df['entity_sentiments'][1]

"[{'name': 'amazon', 'type': 'ORGANIZATION', 'salience': 0.5061889290809631, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 1.7999999523162842}, {'name': 'family', 'type': 'PERSON', 'salience': 0.11175735294818878, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.4000000059604645}, {'name': 'change', 'type': 'OTHER', 'salience': 0.10826481133699417, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.8999999761581421}, {'name': 'one', 'type': 'PERSON', 'salience': 0.09885533154010773, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.800000011920929}, {'name': 'nothing', 'type': 'OTHER', 'salience': 0.033834803849458694, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.4000000059604645}, {'name': 'packages', 'type': 'OTHER', 'salience': 0.03073251061141491, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.4000000059604645}, {'name': 'delivery guy', 'type': 'PERSON', 'salience': 0.030364803969860077, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.4000000059604645}, {'name': 'ones', 'type': 'CONSUMER_GOOD', 'salience': 0.030364803969860077, 'sentiment_score': -0.4000000059604645, 'sentiment_magnitude': 0.4000000059604645}, {'name': 'door', 'type': 'OTHER', 'salience': 0.028247181326150894, 'sentiment_score': -0.5, 'sentiment_magnitude': 0.5}, {'name': 'theft', 'type': 'EVENT', 'salience': 0.021389488130807877, 'sentiment_score': -0.5, 'sentiment_magnitude': 0.5}]"

In [107]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1456 entries, 0 to 1455
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 1456 non-null   object
 1   review               1456 non-null   float64
 2   rating               1456 non-null   int64
 3   company              1456 non-null   object
 4   country              1455 non-null   object
 5   date                 1456 non-null   object
 6   topic                1456 non-null   object
 7   content              1456 non-null   object
 8   sentiment_score      1456 non-null   float64
 9   sentiment_magnitude  1456 non-null   float64
 10  entities             1450 non-null   object
 11  entity_sentiments    1456 non-null   object
 12  review_class         1456 non-null   object
 13  positive_reasons     311 non-null    object
 14  negative_reasons     1156 non-null   object
 15  syntax_tokens        1456 non-null   object
 16  detected_language    1456 non-null   object
 17  classifications      1456 non-null   object
dtypes: float64(3), int64(1), object(14)
memory usage: 204.9+ KB

In [108]:
df[df['country'].isnull()]

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications
881,elisabeth garreth,6.0,1,walmart,NaN,2024-10-01 09:27:49,do not trust walmart company as an affiliate,do not trust walmart company if you decide to ...,-0.7,0.7,"company, commissions, walmart, affiliate progr...","[{'name': 'company', 'type': 'ORGANIZATION', '...",Negative,NaN,do not trust walmart company if you decide to ...,"[{'text': 'do', 'part_of_speech': 'VERB'}, {'t...",en,[]

In [109]:
df.loc[881, "country"] = 'No_name'

In [110]:
temp_df = df[df['entities'].isnull()]
temp_df.index

Index([491, 641, 687, 751, 770, 859], dtype='int64')

In [111]:
df.loc[temp_df.index,'entities'] = 'Not_entity'

In [112]:
df[df['entities'].isnull()]

Empty DataFrame
Columns: [name, review, rating, company, country, date, topic, content, sentiment_score, sentiment_magnitude, entities, entity_sentiments, review_class, positive_reasons, negative_reasons, syntax_tokens, detected_language, classifications]
Index: []

In [113]:
temp_df = df[df['positive_reasons'].isnull()]
temp_df

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...","[{'name': 'orders', 'type': 'OTHER', 'salience...",Negative,NaN,since july until this month of all my orders 8...,"[{'text': 'since', 'part_of_speech': 'ADP'}, {...",en,"[{'category': '/Shopping', 'confidence': 0.629..."
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,as a family we order from amazon almost daily ...,"[{'text': 'as', 'part_of_speech': 'ADP'}, {'te...",en,[]
3,vicki study,1.0,1,amazon,united kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...","[{'name': 'customer service', 'type': 'OTHER',...",Negative,NaN,the customer service has been absolutely appal...,"[{'text': 'the', 'part_of_speech': 'DET'}, {'t...",en,[]
4,jeffrey bruce,5.0,1,amazon,united kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,NaN,amazon are quick enough to take payment for or...,"[{'text': 'amazon', 'part_of_speech': 'NOUN'},...",en,"[{'category': '/Shopping', 'confidence': 0.629..."
5,peter king,8.0,1,amazon,united kingdom,2024-10-01 13:28:58,dodgy delivery information,i have been expecting a delivery from amazon s...,-0.8,0.8,"delivery, amazon, item, sept, courier ups site...","[{'name': 'delivery', 'type': 'EVENT', 'salien...",Negative,NaN,i have been expecting a delivery from amazon s...,"[{'text': 'i', 'part_of_speech': 'PRON'}, {'te...",en,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1449,cassadinegirlaz,1.0,1,bestbuy,united states,2024-03-01 18:09:20,if i could give them negative stars i,if i could give them negative stars i would al...,-0.7,0.7,"guy, letters, keyboard, plan, payment, stars, ...","[{'name': 'guy', 'type': 'PERSON', 'salience':...",Negative,NaN,if i could give them negative stars i would al...,"[{'text': 'if', 'part_of_speech': 'ADP'}, {'te...",en,"[{'category': '/Arts & Entertainment', 'confid..."
1451,tony n,8.0,1,bestbuy,united states,2024-03-01 17:35:48,disgusting service,wish i could give them a minus 5 i purchased a...,-0.6,0.6,"gift, sons, charger, works mower kit, buy, blo...","[{'name': 'gift', 'type': 'OTHER', 'salience':...",Negative,NaN,wish i could give them a minus 5 i purchased a...,"[{'text': 'wish', 'part_of_speech': 'VERB'}, {...",en,"[{'category': '/Home & Garden', 'confidence': ..."
1453,m tuck,2.0,2,bestbuy,canada,2024-03-01 16:50:47,bought what i thought was brand new,bought what i thought was brand new computer ...,-0.7,0.7,"computer, computer, computer, email, name, store","[{'name': 'computer', 'type': 'CONSUMER_GOOD',...",Negative,NaN,bought what i thought was brand new computer ...,"[{'text': 'bought', 'part_of_speech': 'VERB'},...",en,[]
1454,connie laubach,1.0,1,bestbuy,united states,2024-03-01 03:27:12,i bought a tv antenna ask them to come,i bought a tv antenna ask them to come hook it...,-0.6,0.6,"tv antenna, inhome, tv, printer, longeri, prob...","[{'name': 'tv antenna', 'type': 'OTHER', 'sali...",Negative,NaN,i bought a tv antenna ask them to come hook it...,"[{'text': 'i', 'part_of_speech': 'PRON'}, {'te...",en,[]
1455,christine champion,2.0,1,bestbuy,united states,2024-03-01 18:57:53,never delivered the product,never delivered the product their shipper says...,-0.7,0.7,"shipper, photos, product, photos, link, items,...","[{'name': 'shipper', 'type': 'ORGANIZATION', '...",Negative,NaN,never delivered the product their shipper says...,"[{'text': 'never', 'part_of_speech': 'ADV'}, {...",en,[{'category': '/Business & Industrial/Transpor...

In [114]:
df.loc[temp_df.index, 'positive_reasons'] = 'No_Positive'

In [115]:
temp_df = df[df['negative_reasons'].isnull()]
temp_df

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications
2,da,21.0,5,amazon,united kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...","[{'name': 'store', 'type': 'LOCATION', 'salien...",Positive,probably the only store that 1 delivers ontime...,NaN,"[{'text': 'probably', 'part_of_speech': 'ADV'}...",en,[]
9,angel perez,6.0,5,amazon,united states,2024-10-01 12:08:17,amazon is simply excellent,amazon is simply excellent every time ive made...,0.8,0.8,"amazon, purchase ive, amazon, service, platfor...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Positive,amazon is simply excellent every time ive made...,NaN,"[{'text': 'amazon', 'part_of_speech': 'NOUN'},...",en,"[{'category': '/Shopping/Consumer Resources', ..."
18,mr barry,28.0,4,amazon,ireland,2024-10-01 09:24:17,i find the company to be overall in tune with ...,speaking purely as a buyer never sold on the p...,0.1,0.1,"case, buyer, platform, something, ones, ive, c...","[{'name': 'case', 'type': 'OTHER', 'salience':...",Positive,speaking purely as a buyer never sold on the p...,NaN,"[{'text': 'speaking', 'part_of_speech': 'VERB'...",en,[]
24,linda weaver,32.0,5,amazon,united kingdom,2024-10-01 10:06:38,always reliable great service,thankyou to amazon my items always arrive on...,0.9,0.9,"thankyou, items, goods, company, condition, go...","[{'name': 'thankyou', 'type': 'OTHER', 'salien...",Positive,thankyou to amazon my items always arrive on...,NaN,"[{'text': 'thankyou', 'part_of_speech': 'NOUN'...",en,"[{'category': '/Shopping', 'confidence': 0.649..."
38,ginger miller,1.0,5,amazon,united states,2024-10-01 09:13:53,amazon came through when needed,hurricane milton was due to hit on thursday th...,0.1,0.1,"hurricane milton, amazon, amazon, storm, paper...","[{'name': 'hurricane milton', 'type': 'PERSON'...",Positive,hurricane milton was due to hit on thursday th...,NaN,"[{'text': 'hurricane', 'part_of_speech': 'NOUN...",en,[]
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1424,jason bruno,1.0,5,bestbuy,united states,2024-04-01 19:07:46,once in a while as a customer youre made to fe...,i already knew what i was shopping for while l...,0.9,0.9,"product, experience, employees, anything, prod...","[{'name': 'product', 'type': 'CONSUMER_GOOD', ...",Positive,i already knew what i was shopping for while l...,NaN,"[{'text': 'i', 'part_of_speech': 'PRON'}, {'te...",en,[]
1430,leonardo deepstone,2.0,5,bestbuy,united states,2024-04-01 07:46:17,goods bought,i bought dji osmo pocket 3 combo package onlin...,0.3,0.3,"combo package, everything","[{'name': 'combo package', 'type': 'OTHER', 's...",Positive,i bought dji osmo pocket 3 combo package onlin...,NaN,"[{'text': 'i', 'part_of_speech': 'PRON'}, {'te...",en,[]
1432,nick s.,3.0,4,bestbuy,united states,2024-04-01 17:02:04,fantastic for gift cards great staff,this was my first time buying gift cards and i...,0.6,0.6,"time, gift cards, nephews, line, birthday, nyc...","[{'name': 'time', 'type': 'EVENT', 'salience':...",Positive,this was my first time buying gift cards and i...,NaN,"[{'text': 'this', 'part_of_speech': 'DET'}, {'...",en,[{'category': '/Hobbies & Leisure/Special Occa...
1434,linda,11.0,5,bestbuy,united states,2024-04-01 21:45:53,want to leave a great review for our geek squa...,want to leave a great review for our installer...,0.9,0.9,"review, geek squad steven, installer, expectat...","[{'name': 'review', 'type': 'WORK_OF_ART', 'sa...",Positive,want to leave a great review for our installer...,NaN,"[{'text': 'want', 'part_of_speech': 'VERB'}, {...",en,[]
1452,debbie,1.0,5,bestbuy,united states,2024-03-01 15:39:57,happy with purchase,i bought a new laptop there and am very satisf...,0.9,0.9,"laptop, customer service, prices, purchase","[{'name': 'laptop', 'type': 'CONSUMER_GOOD', '...",Positive,i bought a new laptop there and am very satisf...,NaN,"[{'text': 'i', 'part_of_speech': 'PRON'}, {'te...",en,[]

In [116]:
df.loc[temp_df.index, 'negative_reasons'] = 'No_negative'

In [117]:
df['category'] = df['classifications'].str.strip().str.split(',').str.get(0)

In [118]:
df['category']

0                               [{'category': '/Shopping'
1                                                      []
2                                                      []
3                                                      []
4                               [{'category': '/Shopping'
                              ...
1451                       [{'category': '/Home & Garden'
1452                                                   []
1453                                                   []
1454                                                   []
1455    [{'category': '/Business & Industrial/Transpor...
Name: category, Length: 1456, dtype: object

In [119]:
df['confidence'] = df['classifications'].str.strip().str.split(',').str.get(1)

In [120]:
df['confidence']

0        'confidence': 0.6299999952316284}]
1                                       NaN
2                                       NaN
3                                       NaN
4        'confidence': 0.6299999952316284}]
                       ...
1451     'confidence': 0.6399999856948853}]
1452                                    NaN
1453                                    NaN
1454                                    NaN
1455     'confidence': 0.7099999785423279}]
Name: confidence, Length: 1456, dtype: object

In [121]:
df.head()

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,entity_sentiments,review_class,positive_reasons,negative_reasons,syntax_tokens,detected_language,classifications,category,confidence
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...","[{'name': 'orders', 'type': 'OTHER', 'salience...",Negative,No_Positive,since july until this month of all my orders 8...,"[{'text': 'since', 'part_of_speech': 'ADP'}, {...",en,"[{'category': '/Shopping', 'confidence': 0.629...",[{'category': '/Shopping','confidence': 0.6299999952316284}]
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,No_Positive,as a family we order from amazon almost daily ...,"[{'text': 'as', 'part_of_speech': 'ADP'}, {'te...",en,[],[],NaN
2,da,21.0,5,amazon,united kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...","[{'name': 'store', 'type': 'LOCATION', 'salien...",Positive,probably the only store that 1 delivers ontime...,No_negative,"[{'text': 'probably', 'part_of_speech': 'ADV'}...",en,[],[],NaN
3,vicki study,1.0,1,amazon,united kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...","[{'name': 'customer service', 'type': 'OTHER',...",Negative,No_Positive,the customer service has been absolutely appal...,"[{'text': 'the', 'part_of_speech': 'DET'}, {'t...",en,[],[],NaN
4,jeffrey bruce,5.0,1,amazon,united kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...","[{'name': 'amazon', 'type': 'ORGANIZATION', 's...",Negative,No_Positive,amazon are quick enough to take payment for or...,"[{'text': 'amazon', 'part_of_speech': 'NOUN'},...",en,"[{'category': '/Shopping', 'confidence': 0.629...",[{'category': '/Shopping','confidence': 0.6299999952316284}]

In [122]:
df.drop(columns=['entity_sentiments', 'syntax_tokens', 'classifications'], inplace=True)

In [123]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1456 entries, 0 to 1455
Data columns (total 17 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   name                 1456 non-null   object
 1   review               1456 non-null   float64
 2   rating               1456 non-null   int64
 3   company              1456 non-null   object
 4   country              1456 non-null   object
 5   date                 1456 non-null   object
 6   topic                1456 non-null   object
 7   content              1456 non-null   object
 8   sentiment_score      1456 non-null   float64
 9   sentiment_magnitude  1456 non-null   float64
 10  entities             1456 non-null   object
 11  review_class         1456 non-null   object
 12  positive_reasons     1456 non-null   object
 13  negative_reasons     1456 non-null   object
 14  detected_language    1456 non-null   object
 15  category             1456 non-null   object
 16  confidence           700 non-null    object
dtypes: float64(3), int64(1), object(13)
memory usage: 193.5+ KB

In [124]:
df['category'] = df['category'].str.strip().str.split(':').str.get(1)

In [125]:
df['category'] = df['category'].str.strip().str.split('/').str.get(1)

In [126]:
df['category'] = df['category'].astype('str').str.replace('[', '').str.replace(']', '').str.replace(',', '').str.strip()

In [128]:
df['confidence'] = df['confidence'].str.extract(r'(\d+\.\d{2})')

In [130]:
df['negative_reasons'] = df['negative_reasons'].str.lower()

In [131]:
df['positive_reasons'] = df['positive_reasons'].str.lower()

In [132]:
df.head()

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,review_class,positive_reasons,negative_reasons,detected_language,category,confidence
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...",Negative,no_positive,since july until this month of all my orders 8...,en,Shopping',0.62
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...",Negative,no_positive,as a family we order from amazon almost daily ...,en,nan,NaN
2,da,21.0,5,amazon,united kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...",Positive,probably the only store that 1 delivers ontime...,no_negative,en,nan,NaN
3,vicki study,1.0,1,amazon,united kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...",Negative,no_positive,the customer service has been absolutely appal...,en,nan,NaN
4,jeffrey bruce,5.0,1,amazon,united kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...",Negative,no_positive,amazon are quick enough to take payment for or...,en,Shopping',0.62

In [137]:
positive_words = ['excellent', 'good', 'great', 'satisfied', 'happy', 'fantastic', 'positive', 'amazing', 'love', 'wonderful','Helpful', 'Responsive', 'Friendly', 'Quick', 'Efficient', 'Resolved', 'Polite', 'Courteous', 'Professional', 'Supportive', 'Understanding', 'Knowledgeable', 'Prompt', 'Excellent', 'Effective', 'Satisfied', 'Outstanding', 'Pleasant', 'Reliable']
negative_words = ['bad', 'poor', 'disappointed', 'worst', 'negative', 'hate', 'awful', 'terrible', 'unhappy', 'unsatisfied','Rude', 'Unhelpful', 'Slow', 'Unresponsive', 'Frustrating', 'Ignored', 'Unresolved', 'Incompetent', 'Unprofessional', 'Delayed', 'Difficult', 'Angry', 'Disrespectful', 'Confusing', 'Unclear', 'Inconvenient', 'Terrible', 'Poor', 'Disappointed', 'Unreliable','inefficient', 'irritating', 'neglected', 'overlooked', 'careless', 'dismissive', 'unfriendly', 'uncooperative', 'inconsistent', 'unfair', 'overpriced', 'conflicted','stressful', 'defective', 'unacceptable', 'overcomplicated', 'displeased', 'misleading','unpleasant', 'shoddy']

# Function to classify sentiment based on entities
def extract_sentiment_words(entities):
    if isinstance(entities, str):  # Only process if it's a string
        entities_lower = entities.lower()  # Convert to lowercase for case-insensitive matching
        positive_found = [word for word in positive_words if word in entities_lower]
        negative_found = [word for word in negative_words if word in entities_lower]
        
        # Return the words found, if any, otherwise return 'None'
        if positive_found:
            return f"Positive words: {', '.join(positive_found)}"
        elif negative_found:
            return f"Negative words: {', '.join(negative_found)}"
        else:
            return 'None'
    return 'None'  # Default for non-text entries

# Apply the function to extract the sentiment words
df['sentiment_words'] = df['entities'].astype('str').apply(extract_sentiment_words)

In [138]:
df.head()

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,review_class,positive_reasons,negative_reasons,detected_language,category,confidence,sentiment_words
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...",Negative,no_positive,since july until this month of all my orders 8...,en,Shopping',0.62,None
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...",Negative,no_positive,as a family we order from amazon almost daily ...,en,nan,NaN,None
2,da,21.0,5,amazon,united kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...",Positive,probably the only store that 1 delivers ontime...,no_negative,en,nan,NaN,None
3,vicki study,1.0,1,amazon,united kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...",Negative,no_positive,the customer service has been absolutely appal...,en,nan,NaN,None
4,jeffrey bruce,5.0,1,amazon,united kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...",Negative,no_positive,amazon are quick enough to take payment for or...,en,Shopping',0.62,Negative words: worst

In [135]:
df.head()

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,review_class,positive_reasons,negative_reasons,detected_language,category,confidence,sentiment_words
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...",Negative,no_positive,since july until this month of all my orders 8...,en,Shopping',0.62,None
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...",Negative,no_positive,as a family we order from amazon almost daily ...,en,nan,NaN,None
2,da,21.0,5,amazon,united kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...",Positive,probably the only store that 1 delivers ontime...,no_negative,en,nan,NaN,None
3,vicki study,1.0,1,amazon,united kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...",Negative,no_positive,the customer service has been absolutely appal...,en,nan,NaN,None
4,jeffrey bruce,5.0,1,amazon,united kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...",Negative,no_positive,amazon are quick enough to take payment for or...,en,Shopping',0.62,Negative words: worst

In [140]:
df.drop(columns=['sentiment_words'], inplace=True)

In [144]:
df['review_class'] = df['review_class'].str.strip().str.lower()

In [145]:
df['category'] = df['category'].str.strip().str.lower()

In [146]:
df.head()

,name,review,rating,company,country,date,topic,content,sentiment_score,sentiment_magnitude,entities,review_class,positive_reasons,negative_reasons,detected_language,category,confidence
0,vladimiro mascaro,3.0,1,amazon,united kingdom,2024-10-01 18:25:37,4 months of total incopetence,since july until this month of all my orders 8...,-0.6,0.6,"orders, orders, thing, direct debit, headphone...",negative,no_positive,since july until this month of all my orders 8...,en,shopping',0.62
1,lucy loo,9.0,1,amazon,united kingdom,2024-10-01 09:57:32,driver stealing,as a family we order from amazon almost daily ...,-0.8,0.8,"amazon, family, change, one, nothing, packages...",negative,no_positive,as a family we order from amazon almost daily ...,en,nan,NaN
2,da,21.0,5,amazon,united kingdom,2024-10-01 11:36:09,where is the negativity coming from,probably the only store that 1 delivers ontime...,0.1,0.1,"store, customers, prices, competitors, valuefo...",positive,probably the only store that 1 delivers ontime...,no_negative,en,nan,NaN
3,vicki study,1.0,1,amazon,united kingdom,2024-10-01 15:36:33,absolutely appalling customer service,the customer service has been absolutely appal...,-0.7,0.7,"customer service, calls, ive, fault, issue, am...",negative,no_positive,the customer service has been absolutely appal...,en,nan,NaN
4,jeffrey bruce,5.0,1,amazon,united kingdom,2024-10-01 17:09:02,amazon are quick enough to take payment,amazon are quick enough to take payment for or...,-0.7,0.7,"amazon, payment, orders, worst, claim, custome...",negative,no_positive,amazon are quick enough to take payment for or...,en,shopping',0.62

In [148]:
df.to_csv('review_dataset_v2.csv', index=False)